# Generated by Django 4.1.4 on 2023-02-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_branch_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
    ]
