# Generated by Django 4.1.4 on 2023-02-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('department', models.CharField(choices=[('mechatronics', 'MECHATRONICS'), ('mechanical', 'MECHANICAL'), ('computer', 'COMPUTER'), ('civil', 'CIVIL'), ('autoMobile', 'AUTOMOBILE')], max_length=16)),
                ('purposes', models.CharField(choices=[('general', 'GENERAL'), ('fees', 'FEES'), ('leave', 'LEAVE'), ('academic', 'ACADEMIC')], max_length=10)),
            ],
        ),
    ]
