# Generated by Django 4.1.4 on 2023-02-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='department',
        ),
        migrations.RemoveField(
            model_name='data',
            name='purposes',
        ),
    ]
