# Generated by Django 4.1.4 on 2023-02-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_remove_data_department_remove_data_purposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='department',
            field=models.CharField(default='MECHANICAL', max_length=15),
        ),
        migrations.AddField(
            model_name='data',
            name='purposes',
            field=models.CharField(default='GENERAL', max_length=10),
        ),
    ]
