# Generated by Django 4.1.4 on 2023-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_data_department_data_purposes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='department',
            field=models.CharField(default='mechanical', max_length=15),
        ),
    ]
