# Generated by Django 4.1.4 on 2023-02-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_alter_data_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='department',
            field=models.CharField(choices=[('general', 'GENERAL'), ('fees', 'FEES'), ('leave', 'LEAVE'), ('academic', 'ACADEMIC')], default='mechanical', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='purposes',
            field=models.CharField(choices=[('mechatronics', 'MECHATRONICS'), ('mechanical', 'MECHANICAL'), ('computer', 'COMPUTER'), ('civil', 'CIVIL'), ('autoMobile', 'AUTOMOBILE')], default='GENERAL', max_length=100),
        ),
    ]
