# Generated by Django 4.1.4 on 2023-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_alter_data_department_alter_data_purposes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='department',
            field=models.CharField(choices=[('mechatronics', 'MECHATRONICS'), ('mechanical', 'MECHANICAL'), ('computer', 'COMPUTER'), ('civil', 'CIVIL'), ('autoMobile', 'AUTOMOBILE')], default='MECHANICAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='purposes',
            field=models.CharField(choices=[('general', 'GENERAL'), ('fees', 'FEES'), ('leave', 'LEAVE'), ('academic', 'ACADEMIC')], default='GENERAL', max_length=100),
        ),
    ]
