# Generated by Django 4.1.4 on 2023-02-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_alter_data_department_alter_data_purposes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
