# Generated by Django 4.1.4 on 2023-02-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_rename_dob_data_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
